#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
股票分析报告生成模块
生成 Markdown、PDF 格式的分析报告
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Optional
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


class ReportGenerator:
    """报告生成器"""
    
    def __init__(self, output_dir: str = 'reports'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
    
    def generate_daily_report(self, analysis_results: List[Dict], 
                              sentiment_results: List[Dict],
                              date: str = None) -> str:
        """
        生成每日分析报告
        
        Args:
            analysis_results: 技术分析 + 基本面分析结果
            sentiment_results: 舆情分析结果
            date: 报告日期（默认今天）
        
        Returns:
            报告文件路径
        """
        if date is None:
            date = datetime.now().strftime('%Y-%m-%d')
        
        report_date = datetime.now().strftime('%Y年%m月%d日 %H:%M')
        
        # 生成 Markdown 报告
        md_content = self._build_markdown_report(analysis_results, sentiment_results, report_date)
        
        # 保存文件
        filename = f'daily_report_{date}.md'
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        logger.info(f"日报已生成：{filepath}")
        
        # 同时生成摘要版本
        summary_path = self._generate_summary(analysis_results, sentiment_results, date)
        
        return filepath
    
    def _build_markdown_report(self, analysis_results: List[Dict], 
                               sentiment_results: List[Dict],
                               report_date: str) -> str:
        """构建 Markdown 报告内容"""
        
        md = f"""# 📊 股票分析日报

**报告日期**: {report_date}

---

## 📈 市场概览

共分析 **{len(analysis_results)}** 只股票

"""
        
        # 评级统计
        ratings = {}
        for r in analysis_results:
            rating = r.get('rating', {}).get('rating', '未知')
            ratings[rating] = ratings.get(rating, 0) + 1
        
        md += "### 评级分布\n\n"
        for rating, count in sorted(ratings.items(), key=lambda x: ['强烈推荐', '推荐', '中性', '谨慎', '回避'].index(x[0]) if x[0] in ['强烈推荐', '推荐', '中性', '谨慎', '回避'] else 99):
            bar = '█' * count
            md += f"- {rating}: {count} {bar}\n"
        
        md += "\n---\n\n"
        
        # 个股详细分析
        md += "## 📋 个股分析\n\n"
        
        for result in analysis_results:
            md += self._format_stock_analysis(result)
        
        # 舆情汇总
        md += "\n---\n\n"
        md += "## 📰 舆情监控\n\n"
        
        for sentiment in sentiment_results:
            md += self._format_sentiment(sentiment)
        
        # 投资建议
        md += "\n---\n\n"
        md += "## 💡 投资建议\n\n"
        md += self._generate_investment_advice(analysis_results, sentiment_results)
        
        # 免责声明
        md += """
---

## ⚠️ 免责声明

本报告由 AI 自动生成，仅供参考，不构成投资建议。

股市有风险，投资需谨慎。请结合个人情况独立判断。

---

*Generated by Stock Analysis Agent*
"""
        
        return md
    
    def _format_stock_analysis(self, result: Dict) -> str:
        """格式化个股分析"""
        name = result.get('name', '未知')
        code = result.get('stock_code', '')
        market = result.get('market', '')
        
        rating = result.get('rating', {})
        rating_text = rating.get('rating', '未知')
        score = rating.get('score', 0)
        
        # 评级图标
        rating_icon = {'强烈推荐': '🟢', '推荐': '🟡', '中性': '⚪', '谨慎': '🟠', '回避': '🔴'}.get(rating_text, '⚪')
        
        md = f"""### {rating_icon} {name} ({code})

**综合评级**: {rating_text} ({score}分)

"""
        
        # 技术指标
        tech = result.get('technical', {})
        if tech and not tech.get('error'):
            indicators = tech.get('indicators', {})
            trend = tech.get('trend', '未知')
            signals = tech.get('signals', [])
            
            md += f"""**技术指标**
| 指标 | 数值 |
|------|------|
| 当前价 | {indicators.get('MA5', 0)} |
| MA5 | {indicators.get('MA5', 0)} |
| MA10 | {indicators.get('MA10', 0)} |
| MA20 | {indicators.get('MA20', 0)} |
| MA60 | {indicators.get('MA60', 0)} |
| RSI | {indicators.get('RSI', 0)} |
| MACD | {indicators.get('MACD', 0)} |

**趋势**: {trend}

**技术信号**:
"""
            if signals:
                for s in signals:
                    signal_icon = {'买入': '📈', '卖出': '📉', '观望': '⏸️'}.get(s.get('signal'), '•')
                    md += f"- {signal_icon} {s.get('desc', '')}\n"
            else:
                md += "- 无明显信号\n"
        
        # 基本面
        fund = result.get('fundamental', {})
        if fund and not fund.get('error'):
            metrics = fund.get('metrics', {})
            scores = fund.get('scores', {})
            evaluation = fund.get('evaluation', '')
            
            md += f"""
**基本面指标**
| 指标 | 数值 |
|------|------|
| PE(TTM) | {metrics.get('PE', 0)} |
| PB | {metrics.get('PB', 0)} |
| ROE | {metrics.get('ROE', 0)}% |
| 营收增长 | {metrics.get('revenue_growth', 0)}% |
| 利润增长 | {metrics.get('profit_growth', 0)}% |
| 资产负债率 | {metrics.get('debt_ratio', 0)}% |

**基本面评分**: {scores.get('total', 0)}分 - {evaluation}

"""
        
        md += "\n---\n\n"
        return md
    
    def _format_sentiment(self, sentiment: Dict) -> str:
        """格式化舆情分析"""
        name = sentiment.get('stock_name', '未知')
        code = sentiment.get('stock_code', '')
        
        sent = sentiment.get('sentiment', {})
        sentiment_text = sent.get('sentiment', 'neutral')
        sentiment_score = sent.get('score', 0.5)
        news_count = sent.get('news_count', 0)
        
        # 情绪图标
        sentiment_icon = {'positive': '😊', 'negative': '😟', 'neutral': '😐'}.get(sentiment_text, '😐')
        
        md = f"""### {name} ({code})

- **市场情绪**: {sentiment_icon} {sentiment_text} ({sentiment_score})
- **相关新闻**: {news_count} 条
- **正面提及**: {sent.get('positive_count', 0)}
- **负面提及**: {sent.get('negative_count', 0)}

"""
        
        # 最新新闻
        latest_news = sent.get('latest_news', [])
        if latest_news:
            md += "**最新新闻**:\n\n"
            for news in latest_news[:3]:
                title = news.get('title', '')
                source = news.get('source', '')
                time = news.get('publish_time', '')
                md += f"- [{title}]({news.get('url', '#')}) - {source} {time}\n"
        
        md += "\n"
        return md
    
    def _generate_investment_advice(self, analysis_results: List[Dict], 
                                    sentiment_results: List[Dict]) -> str:
        """生成投资建议"""
        
        # 找出强烈推荐和推荐的股票
        strong_buy = [r for r in analysis_results if r.get('rating', {}).get('rating') == '强烈推荐']
        buy = [r for r in analysis_results if r.get('rating', {}).get('rating') == '推荐']
        avoid = [r for r in analysis_results if r.get('rating', {}).get('rating') == '回避']
        
        advice = ""
        
        if strong_buy:
            advice += "**重点关注**:\n\n"
            for r in strong_buy:
                advice += f"- 🟢 {r.get('name', '')} ({r.get('stock_code', '')}) - 综合评分 {r.get('rating', {}).get('score', 0)}分\n"
            advice += "\n"
        
        if buy:
            advice += "**可适当配置**:\n\n"
            for r in buy:
                advice += f"- 🟡 {r.get('name', '')} ({r.get('stock_code', '')}) - 综合评分 {r.get('rating', {}).get('score', 0)}分\n"
            advice += "\n"
        
        if avoid:
            advice += "**建议规避**:\n\n"
            for r in avoid:
                advice += f"- 🔴 {r.get('name', '')} ({r.get('stock_code', '')}) - 综合评分 {r.get('rating', {}).get('score', 0)}分\n"
            advice += "\n"
        
        # 总体建议
        if len(strong_buy) + len(buy) > len(analysis_results) / 2:
            advice += "**总体建议**: 市场机会较多，可积极布局优质标的\n"
        elif len(avoid) > len(analysis_results) / 3:
            advice += "**总体建议**: 市场风险较大，建议谨慎观望\n"
        else:
            advice += "**总体建议**: 市场分化明显，建议精选个股\n"
        
        return advice
    
    def _generate_summary(self, analysis_results: List[Dict], 
                          sentiment_results: List[Dict], 
                          date: str) -> str:
        """生成简报（用于快速查看）"""
        
        summary = f"""📊 股票日报 | {date}

【市场概览】
共分析 {len(analysis_results)} 只股票

【评级分布】
"""
        
        ratings = {}
        for r in analysis_results:
            rating = r.get('rating', {}).get('rating', '未知')
            ratings[rating] = ratings.get(rating, 0) + 1
        
        for rating, count in ratings.items():
            summary += f"  {rating}: {count}\n"
        
        summary += "\n【重点关注】\n"
        
        top_stocks = sorted(analysis_results, 
                           key=lambda x: x.get('rating', {}).get('score', 0), 
                           reverse=True)[:3]
        
        for r in top_stocks:
            summary += f"  🟢 {r.get('name', '')} ({r.get('rating', {}).get('score', 0)}分)\n"
        
        filepath = os.path.join(self.output_dir, f'summary_{date}.txt')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(summary)
        
        logger.info(f"简报已生成：{filepath}")
        return filepath
    
    def generate_weekly_report(self, daily_reports: List[str]) -> str:
        """生成周报（汇总多日数据）"""
        # TODO: 实现周报生成
        logger.info("周报功能开发中...")
        return ""


if __name__ == '__main__':
    # 测试
    generator = ReportGenerator()
    
    # 模拟数据
    test_results = [
        {
            'name': '测试股票',
            'stock_code': '000001',
            'market': 'SZ',
            'rating': {'rating': '推荐', 'score': 75},
            'technical': {
                'trend': '上升趋势',
                'indicators': {'MA5': 10.5, 'MA10': 10.2, 'RSI': 55},
                'signals': [{'signal': '买入', 'desc': 'MA 金叉'}]
            },
            'fundamental': {
                'metrics': {'PE': 15, 'PB': 2, 'ROE': 12},
                'scores': {'total': 70},
                'evaluation': '良好'
            }
        }
    ]
    
    test_sentiment = [
        {
            'stock_name': '测试股票',
            'stock_code': '000001',
            'sentiment': {
                'sentiment': 'positive',
                'score': 0.7,
                'news_count': 10,
                'positive_count': 7,
                'negative_count': 3,
                'latest_news': []
            }
        }
    ]
    
    filepath = generator.generate_daily_report(test_results, test_sentiment)
    print(f"报告已生成：{filepath}")
